### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/toolbarr#33]
- [ ] Improve INFO logging.
- [ ] Look for places to WARN log.
- [ ] Forms vs basic auth fixes.
- [ ] Do sqlite3 queries correctly (no `sprintf`).
- [ ] Move initialize.js code to Starr library.
- [ ] Fix Radarr icon in menu bar.

**Comment by bakerboy448** [comment]
Add CF bulk delete via API
